dependencies:
  - python=3.7
  - pip
  - pip:
    - ..  # d2l
    - git+https://github.com/d2l-ai/d2l-book
    - mxnet-cu101==1.6.0
    - torch==1.5.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
    - torchvision