dependencies:
  - python=3.9
  - pip
  - pip:
    - ..  # d2l
    - mxnet-cu102==1.7.0
    - torch==1.12.0+cu102
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.13.0+cu102
    - -f https://download.pytorch.org/whl/torch_stable.html
    - tensorflow==2.9.1
    - tensorflow-probability==0.17.0
    - tensorflow-datasets
    - jaxlib
    - "jax[cuda]"
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - flax
