dependencies:
  - python=3.7
  - pip
  - pip:
    - ..  # d2l
    - git+https://github.com/d2l-ai/d2l-book
    - mxnet-cu101==1.7.0
    - torch==1.8.0.dev20201219+cu101
    - --pre
    - -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
    - torchvision==0.9.0.dev20201219+cu101
    - --pre
    - -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
    - tensorflow==2.3.1
    - tensorflow-probability==0.11.1
