dependencies:
  - python=3.8
  - pip
  - pip:
    - ..  # d2l
    - git+https://github.com/d2l-ai/d2l-book
    - mxnet-cu101==1.7.0
    - torch==1.8.1+cu101
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.9.1+cu101
    - -f https://download.pytorch.org/whl/torch_stable.html
    - tensorflow==2.3.1
    - tensorflow-probability==0.11.1
